name: Update Coverage Badges and Summary

# Trigger the workflow on pushes to the main branch
on:
  push:
    branches:
      - main

jobs:
  update-assets:
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.2.0

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Install required dependencies for Puppeteer
      - name: Install Chromium dependencies
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install -y libnss3 libatk1.0-0 libx11-xcb1 libcups2 fonts-liberation
          sudo apt-get install -y libxshmfence1 libgbm1 libxcomposite1 libxrandr2 libgtk-3-0 libpangocairo-1.0-0

      # Step 4: Run tests and generate coverage report
      - name: Run test coverage
        run: npm run test:coverage

      # Step 5: Generate coverage assets (badges and summary)
      - name: Generate coverage assets
        run: npm run generate-coverage-assets

      # Step 6: Commit and push updated assets
      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add badges/*.svg badges/coverage-summary.png
          git commit -m "chore: update coverage badges and summary"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
