name: Update Coverage Badges and Summary

# Trigger the workflow on pushes to the main branch
on:
  push:
    branches:
      - main

jobs:
  update-assets:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests and generate coverage report
      - name: Run test coverage
        run: npm run test:coverage

      # Step 5: Generate coverage assets (badges and summary)
      - name: Generate coverage assets
        run: npm run generate-coverage-assets

      # Step 6: Commit and push updated assets
      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add badges/*.svg badges/coverage-summary.png
          git commit -m "chore: update coverage badges and summary"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
